In [1]:
import numpy as np

In [3]:
array = np.arange(11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
cond = array > 5
cond

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [6]:
cond2 = (array > 5) & (array < 9)
cond2

array([False, False, False, False, False, False,  True,  True,  True,
       False, False])

In [7]:
cond3 = (array > 5) | (array < 9)
cond3

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])