In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4,5]

In [3]:
array = np.array(lista)

In [4]:
array*2

array([ 2,  4,  6,  8, 10])

In [5]:
lista*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [8]:
# raiz quadrada
np.sqrt(array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [9]:
narray = [2.8, 2.3, 1.6, 1.2, 1.94]

In [10]:
# aredondar tudo para cima
np.ceil(narray)

array([3., 3., 2., 2., 2.])

In [11]:
# aredondar para baixo
np.floor(narray)

array([2., 2., 1., 1., 1.])

In [13]:
np.around(narray, 1)

array([2.8, 2.3, 1.6, 1.2, 1.9])