In [1]:
import numpy as np

In [2]:
array = np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#slicing
array[2:6]

array([3, 4, 5, 6])

In [4]:
array[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
array[5:]

array([ 6,  7,  8,  9, 10])

In [6]:
array[::2]

array([1, 3, 5, 7, 9])